### ISSUE TITLE
composer deps not correct

### ISSUE THREAD

**Issue by philippfrenzel** [schmunk42/yii2-packaii#10]
try composer.phar update...

**Comment by schmunk42** [comment]
Did this today without problems, what's your problem?

**Comment by philippfrenzel** [comment]
Problem 1
    - schmunk42/yii2-packaii dev-tonydspaniard requires cebe/yii2-gravatar 1.\* -> no matching package found.
    - schmunk42/yii2-packaii dev-schmunk requires cebe/yii2-gravatar 1.\* -> no matching package found.
    - schmunk42/yii2-packaii dev-master requires cebe/yii2-gravatar 1.\* -> no matching package found.
    - Installation request for schmunk42/yii2-packaii \* -> satisfiable by schmunk42/yii2-packaii[dev-master, dev-schmunk, dev-tonydspaniard].

**Comment by schmunk42** [comment]
Umm, do you use a custom repo in your composer.json?
What does `show cebe/yii2-gravatar` say?

```
$ composer.phar show cebe/yii2-gravatar
name     : cebe/yii2-gravatar
descrip. : Gravatar Widget for Yii 2
keywords : gravatar, yii
versions : dev-master, * 1.1, 1.0
type     : yii2-extension
license  : MIT
source   : [git] https://github.com/cebe/yii2-gravatar.git c9c01bd14c9bdee9e5ae1ef1aad23f80c182c057
dist     : [zip] https://api.github.com/repos/cebe/yii2-gravatar/zipball/c9c01bd14c9bdee9e5ae1ef1aad23f80c182c057 c9c01bd14c9bdee9e5ae1ef1aad23f80c182c057
names    : cebe/yii2-gravatar

autoload
psr-0
cebe\gravatar\ => .

requires
yiisoft/yii2 *
```

**Comment by philippfrenzel** [comment]
name     : cebe/yii2-gravatar
descrip. : Gravatar Widget for Yii 2
keywords : gravatar, yii
versions : \* dev-master, 1.1, 1.0
type     : yii2-extension
license  : MIT
source   : [git] https://github.com/cebe/yii2-gravatar.git dcb4b248f2c7980c515951251935f468e7a8d047
dist     : [zip] https://api.github.com/repos/cebe/yii2-gravatar/zipball/dcb4b248f2c7980c515951251935f468e7a8d047 dcb4b248f2c7980c515951251935f468e7a8d047
names    : cebe/yii2-gravatar

autoload
psr-0
cebe\gravatar\ => .

requires
yiisoft/yii2 *

**Comment by schmunk42** [comment]
Do you have cebe/yii2-gravatar:dev-master in your root composer.json?

Von meinem iPhone gesendet

**Comment by philippfrenzel** [comment]
yes, I changed it to 1.\* for "test" and now it works like charm!!! It's really cool! I like the browser...

**Comment by schmunk42** [comment]
Thx. If you don't need it in your application, just remove it from your root composer.json

If you want dev-master for some reason, you could use 'dev-master as 1.2'

Von meinem iPhone gesendet
